name: SAML Server Docker Build and Push

on:
  push:
    branches:
      - "stable"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: beyondfuture
          password: mollatech!@#$1234

      - name: SAML Server Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          push: true
          tags: beyondfuture/single-sign-on-saml:v1,beyondfuture/single-sign-on-saml:latest,
